### PR TITLE
Add getters and conversion method to basic counts

### PR DESCRIPTION
**Pull request by Lithimlin**
I've added getter methods for the values ATIME, ASTEP, TINT, and the gain.
Said methods are then used in the new method `toBasicCounts` which converts the values returned by the ADC to "Basic Count" values as described in [the Application Note (Section 3.1) for the AS7341](https://ams.com/documents/20143/36005/AS7341_AN000633_1-00.pdf/fc552673-9800-8d60-372d-fc67cf075740).

None of the already existing code was changed.

### CODE REVIEW

**Comment by Lithimlin** [comment]
I'm not sure what went wrong here. The error message is not really telling of what actually happened...

**Comment by siddacious** [comment]
Hi there, thank you for your contribution. To get details about the failure you'll have to click the "Details" link next to the failing review:

image

then expand the node for the failing step, in this case the clang formatting:

image

In the expanded node you can see the diff that was created when `clang-format` was applied to the code from the PR. This check tests that the code to be formatted using clang-format and will fail if it sees that running `clang-format` would create changes:

image

There are more changes beyond what is in the screenshot. You can try to appease clang by manually applying the changes however I would recommend that you make `clang-format` do it by using the `-i` flag which applies the changes in place:
`clang-format -i Adafruit_AS7341.*`

Please @ me if you have any questions

**Comment by Lithimlin** [comment]
Thanks. I had tried looking at the message but I missed the difference in spacing so I was confused what the problem was.
Thanks a lot for the help!

**Comment by Lithimlin** [comment]
@siddacious I'm pretty sure that these documentation fails are not caused by my implementation...

**Comment by siddacious** [comment]
@Lithimlin you are correct! The doxygen errors were due to me merging code without docs :\

I've added the docs in question so it should stop complaining if you merge master into your branch/fork and re-push

edit: nope! please stand by

**Comment by siddacious** [comment]
ok @Lithimlin, master is back to normal. Please merge and push to your branch and it should pass unless there's any issues with your PR

**Comment by Lithimlin** [comment]
@siddacious This is ready to be merged

**Review by siddacious — CHANGES_REQUESTED** [review]
@Lithimlin Hi! Sorry for letting this ball sit in my court for so long. I was able to verify that nothing is broken, however it would help me verify the added behavior if you could add a simple example  that shows how to use the new features.

Once I can get that and verify the new behavior I'll merge

**Comment by Lithimlin** [comment]
I've added an example for the conversion to basic counts. Internally, it uses the newly implemented getter methods.

**Comment by Lithimlin** [comment]
@siddacious let me know if there's anything still missing. Otherwise it should be ready now.

**Comment by siddacious** [comment]
works great @Lithimlin , thanks for the contrib and apologies for the delay

**Pull request merged**
